### ISSUE TITLE
minibatch_size=1 on policy make an NAN training results? 

### ISSUE THREAD

**Issue by Felixvillas** [WeihaoTan/TWOSOME#3]
Hi~
I set `args.policy_num_minibatches == (args.num_envs * args.num_steps)`, then `args.policy_minibatch_size=1`. After the first epoch update (I set `args.update_epochs=1`), the next inference `action, logprob, _, value = agent.get_action_and_value(next_obs)` obtains an `NAN` on `outputs = self.actor(input_ids, attention_mask=attention_mask)`.

Did you observe the same thing during the experiment? I'm not quite sure why. Could you explain it to me?

**Comment by WeihaoTan** [comment]
Hi. Thanks for reaching out. I never tried to set args.policy_minibatch_size=1 and did not observe this situation previously. But please do not set the minibatch size to 1, otherwise, you will only use 1 state to update the policy every time, which will cause a huge variance and I guess the NAN is also caused by it. Please set the minibatch size to a reasonable number, like at least 8 (16 32 64 would be better), even if you do not have enough GPU memory.

**Comment by Felixvillas** [comment]
> Hi. Thanks for reaching out. I never tried to set args.policy_minibatch_size=1 and did not observe this situation previously. But please do not set the minibatch size to 1, otherwise, you will only use 1 state to update the policy every time, which will cause a huge variance and I guess the NAN is also caused by it. Please set the minibatch size to a reasonable number, like at least 8 (16 32 64 would be better), even if you do not have enough GPU memory.

Thanks for reply~ I'll close this issue @WeihaoTan
